version: '3.8'

services:
  backend:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend
