sonar.projectKey=mukesh0097-pro_Customer-support-Saas
sonar.organization=mukesh0097-pro
sonar.projectName=SupportAI SaaS
sonar.sources=project/backend/src,project/frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**
sonar.sourceEncoding=UTF-8
